export interface Package {
  name: string
  /** One-liner shown on the package cards and used by the search filter. */
  description: string
  /** A fuller paragraph, shown on hover in the parallax showcase. */
  longDescription: string
  commands: string[]
  path: string
  icon: string
  /**
   * Cover image under `public/`. Generated by
   * `bun ./scripts/generate-package-covers.tsx` — re-run it after editing a
   * package's name, description, icon or commands here.
   */
  image: string
  /** Where the showcase links to: the docs page, or GitHub when there is none. */
  href: string
}

export interface Category {
  name: string
  iconKey: string
  description: string
  color: string
  packages: Package[]
}

export const REPO_URL = "https://github.com/OpenSourceAGI/dev-tools-starter-agent"

const github = (path: string) => `${REPO_URL}/tree/master/${path}`

export const categories: Category[] = [
  {
    name: "Apps",
    iconKey: "app",
    description: "Full-featured applications for development and infrastructure",
    color: "brand",
    packages: [
      {
        name: "dev-tools-help-docs",
        icon: "FileText",
        description: "Documentation site built with Next.js featuring AI chat, full-text search, and auto-generated API reference from TypeScript types and OpenAPI specs.",
        longDescription: "The site you are reading. Fumadocs on Next.js with an AI assistant that searches and cites the docs, Orama full-text search, and an API reference generated straight from TypeScript types and OpenAPI specs. Every package README in the monorepo is synced in as a page, and dependency graphs and file trees are rendered live by code-tree-graph.",
        commands: ["bun dev", "bun run docs:sync"],
        path: "apps/dev-tools-help-docs/",
        image: "/packages/dev-tools-help-docs.svg",
        href: "/docs",
      },
      {
        name: "Cloud-Computer-Control-Panel",
        icon: "Server",
        description: "Open-source cloud infrastructure management platform. Automates Dokploy deployment for container orchestration on AWS EC2 -- provision servers, manage containers, and monitor services.",
        longDescription: "A self-hosted control panel for your own cloud. It provisions AWS EC2 servers, installs Dokploy on them for container orchestration, and gives you one dashboard to deploy apps, manage containers and databases, watch resource usage, and keep credentials in one place — an open alternative to a managed PaaS that runs on hardware you own.",
        commands: ["bun dev", "bun run build"],
        path: "apps/Cloud-Computer-Control-Panel/",
        image: "/packages/Cloud-Computer-Control-Panel.svg",
        href: "/docs/apps/Cloud-Computer-Control-Panel",
      },
      {
        name: "cccp-vscode-ext",
        icon: "Cloud",
        description: "The Cloud Computer Control Panel dashboard in the VS Code sidebar, reusing the Next.js app's own React components so provisioning and credential management happen inside the editor.",
        longDescription: "Brings the Cloud Computer Control Panel into a VS Code sidebar view. Rather than re-implementing the UI, the extension mounts the Next.js app's own React components in a webview, so provisioning servers, deploying containers and managing credentials happen without leaving the editor — and stay in sync with the web dashboard.",
        commands: ["bun run compile", "bun run test"],
        path: "apps/cccp-vscode-ext/",
        image: "/packages/cccp-vscode-ext.svg",
        href: "/docs/apps/cccp-vscode-ext",
      },
      {
        name: "vscode-cloud",
        icon: "Code",
        description: "Per-user VS Code (code-server) instances on Cloudflare Containers. Each user gets a fully isolated environment with SSO, SQLite storage, and traffic routing.",
        longDescription: "Runs a private VS Code in the browser for every user. A Cloudflare Worker authenticates with SSO, then routes each user to their own code-server instance on Cloudflare Containers, with session state kept in a Durable Object's SQLite storage. Containers start on demand and sleep when idle, so a fleet of isolated dev environments costs close to nothing at rest.",
        commands: ["bun deploy", "wrangler deploy"],
        path: "apps/vscode-cloud/",
        image: "/packages/vscode-cloud.svg",
        href: "/docs/apps/vscode-cloud",
      },
    ],
  },
  {
    name: "CLI Tools",
    iconKey: "terminal",
    description: "Command-line utilities for development workflows",
    color: "ember",
    packages: [
      {
        name: "about-system-info",
        icon: "Cpu",
        description: "Cross-platform CLI that prints CPU, memory, disk, uptime, public IP, ISP, and installed tools as a compact emoji line.",
        longDescription: "A cross-platform system summary for Windows, macOS and Linux. One command prints CPU, memory, disk, uptime, public IP, ISP and the dev tools you have installed as a compact, emoji-labelled line. Pick individual info blocks, emit JSON for scripts, customise colours, emojis and order in a settings file, and install it as a shell greeting that runs on every new terminal.",
        commands: ["npx about-system", "npm install -g about-system"],
        path: "packages/about-system-info/",
        image: "/packages/about-system-info.svg",
        href: "/docs/packages/about-system-info",
      },
      {
        name: "api2ai-mcp-generator",
        icon: "Wand2",
        description: "Generate production-ready MCP servers from any OpenAPI spec. Supports HTTP, SSE, and Streamable HTTP transports with Zod validation and auth.",
        longDescription: "Point it at any OpenAPI spec and get a working MCP server that lets Claude or ChatGPT call that API. Each operation becomes a tool with Zod-validated input; you can filter tools by tag, method or risk. A three-layer security model classifies risky mutations, enforces a runtime approval policy, and hardens outbound HTTP with a host allowlist and timeouts.",
        commands: ["npx api2ai <openapi-spec-url>", "npm install -g api2ai"],
        path: "packages/api2ai-mcp-generator/",
        image: "/packages/api2ai-mcp-generator.svg",
        href: "/docs/packages/api2ai-mcp-generator",
      },
      {
        name: "create-cloud-db",
        icon: "Database",
        description: "Interactive CLI that creates a Turso edge database and writes credentials directly into your .env file.",
        longDescription: "Skip the dashboard. create-cloud-db creates a Turso (libSQL) edge database, mints an auth token, and writes TURSO_DATABASE_URL and TURSO_AUTH_TOKEN straight into your project's .env — preserving everything else in the file. Ready to plug into Drizzle or any libSQL client within seconds of running it.",
        commands: ["npx create-cloud-db [db-name]", "npm install -g create-cloud-db"],
        path: "packages/create-cloud-db/",
        image: "/packages/create-cloud-db.svg",
        href: "/docs/packages/create-cloud-db",
      },
      {
        name: "create-starter-app",
        icon: "Rocket",
        description: "Interactive CLI to scaffold a starter app from curated templates. Prompts for framework, auth provider, database, and UI library.",
        longDescription: "An arrow-key menu that scaffolds a new project from this repo's curated starter templates — Next.js or SvelteKit, Better Auth, Drizzle or Prisma, shadcn UI, Fumadocs or Docusaurus. It copies the template without node_modules, renames the package, and leaves you with a project that runs on the first bun dev.",
        commands: ["npx create-starter-app", "bun create starter-app"],
        path: "packages/create-starter-app/",
        image: "/packages/create-starter-app.svg",
        href: "/docs/packages/create-starter-app",
      },
      {
        name: "git0-repo-downloader",
        icon: "GitBranch",
        description: "CLI to search GitHub repos by keyword, download source archives or release binaries, install deps, and open in editor.",
        longDescription: "From idea to open editor in one command. Search GitHub by keyword or paste a URL, then git0 downloads the source (or just a sub-folder from a /tree/ link), or the release binary built for your OS and CPU. It detects the project type, installs dependencies with the right package manager, and opens the folder in your IDE.",
        commands: ["npx git0 <repo>", "npm install -g git0"],
        path: "packages/git0-repo-downloader/",
        image: "/packages/git0-repo-downloader.svg",
        href: "/docs/packages/git0-repo-downloader",
      },
      {
        name: "open-when-ready",
        icon: "Globe",
        description: "Smart dev server wrapper that watches output, auto-opens browser when ready, and on error launches your AI assistant.",
        longDescription: "Wrap any dev command and stop babysitting the terminal. open-ready watches the output, opens your browser the moment the server is actually listening, and serves it at a stable https://<name>.localhost URL. When the output shows an error instead, it opens your AI assistant with the error already pasted in.",
        commands: ["npx open-ready <command>", "npm install -g open-ready"],
        path: "packages/open-when-ready/",
        image: "/packages/open-when-ready.svg",
        href: "/docs/packages/open-when-ready",
      },
      {
        name: "server-shell-setup",
        icon: "HardDrive",
        description: "One-command bootstrap for a modern dev environment: installs fish, nvim, nushell, bun, node, helix, starship, docker, and more.",
        longDescription: "Turn a fresh server into a comfortable workstation with one line. It installs fish and nushell, Neovim and Helix, Node via Volta, Bun, Docker, Starship, yazi, code-server and more — interactively or fully unattended — sets your default shell, and adds a curated set of aliases. Works across the major Linux distros.",
        commands: ["wget -qO- tinyurl.com/shellsetup | bash"],
        path: "packages/server-shell-setup/",
        image: "/packages/server-shell-setup.svg",
        href: "/docs/packages/server-shell-setup",
      },
    ],
  },
  {
    name: "Libraries",
    iconKey: "package",
    description: "Reusable packages and components for your projects",
    color: "teal",
    packages: [
      {
        name: "manage-storage",
        icon: "HardDrive",
        description: "Unified storage API for AWS S3, Cloudflare R2, and Backblaze B2. Auto-detects provider from env vars. One StorageManager class: upload, download, list, copy, rename, delete.",
        longDescription: "One API for every S3-compatible bucket. StorageManager reads your env vars, works out whether you are on AWS S3, Cloudflare R2 or Backblaze B2, and gives you upload, download, list, exists, copy, rename and delete. Pass credentials to the constructor instead and the same code runs on Workers and other edge and serverless runtimes.",
        commands: ["npm install manage-storage", "bun add manage-storage"],
        path: "packages/manage-storage/",
        image: "/packages/manage-storage.svg",
        href: "/docs/packages/manage-storage",
      },
      {
        name: "react-app-store-buttons",
        icon: "Smartphone",
        description: "React badge components for 8 app store and platform download links. Detects user OS and highlights matching button.",
        longDescription: "Drop-in download badges for the App Store, Google Play, Chrome Web Store, macOS, Windows, Linux and Snap. Give a store id or a link, and the buttons build the right URL — or a native deep link that opens the store app directly. With autoHighlight on, the badge for the visitor's operating system is brought forward.",
        commands: ["npm install react-app-store-buttons", "bun add react-app-store-buttons"],
        path: "packages/react-app-store-buttons/",
        image: "/packages/react-app-store-buttons.svg",
        href: "/docs/packages/react-app-store-buttons",
      },
      {
        name: "export-svg-icons-typescript",
        icon: "Image",
        description: "Convert a folder of SVG icons into a color-customizable, tree-shakable TypeScript index that works with any component framework.",
        longDescription: "Turns a folder of SVG files into one tree-shakable TypeScript module of icon functions. Each icon takes colour, size, width and height options and returns an SVG string, so it works in React, Svelte, Vue or plain DOM code. Every export carries a JSDoc preview, so you see the icon on hover in your editor.",
        commands: ["npx export-svg-typescript -i ./src/icons", "npm install -g export-svg-typescript"],
        path: "packages/export-svg-icons-typescript/",
        image: "/packages/export-svg-icons-typescript.svg",
        href: "/docs/packages/export-svg-icons-typescript",
      },
    ],
  },
  {
    name: "Infrastructure",
    iconKey: "cloud",
    description: "Deployment and infrastructure automation tools",
    color: "brand",
    packages: [
      {
        name: "cloudflare-to-claude-fix",
        icon: "Zap",
        description: "Cloudflare Workers Queue consumer that fires a Claude Code routine automatically whenever a Workers build fails.",
        longDescription: "Self-healing deploys for Cloudflare Workers. Build events flow into a Cloudflare Queue; when a build fails, this consumer fires a Claude Code routine with the failure details so an agent can investigate and open a fix. Retries and a dead-letter queue make sure no failed build is silently dropped, and an optional webhook pings you as it happens.",
        commands: ["bun deploy", "wrangler deploy"],
        path: "packages/cloudflare-to-claude-fix/",
        image: "/packages/cloudflare-to-claude-fix.svg",
        href: "/docs/packages/cloudflare-to-claude-fix",
      },
      {
        name: "verify-phone-sms",
        icon: "Shield",
        description: "SMS phone verification API server built with Hono on Cloudflare Workers. Sends OTP codes, blocks VoIP, enforces rate limiting.",
        longDescription: "A ready-to-deploy phone verification API. A Hono server on Cloudflare Workers sends one-time codes through AWS SNS, checks them on /api/verify, and rejects VoIP and virtual numbers before you pay to text them. API-key auth and per-number rate limiting are built in, and the OpenAPI spec powers this site's API reference.",
        commands: ["bun deploy", "wrangler deploy"],
        path: "packages/verify-phone-sms/",
        image: "/packages/verify-phone-sms.svg",
        href: "/docs/packages/verify-phone-sms",
      },
      {
        name: "web2mobile-wrapper",
        icon: "MonitorSmartphone",
        description: "Transform any website URL into a native mobile app wrapper for iOS and Android with push notifications.",
        longDescription: "Ship your website to the App Store and Google Play. Give it a URL and it generates an Expo / React Native app that hosts the site in a WebView, auto-detects and resizes your icon and splash assets with Sharp, and includes EAS scripts to build and submit both iOS and Android binaries.",
        commands: ["npx create-mobile-wrapper", "npm install -g create-mobile-wrapper"],
        path: "packages/web2mobile-wrapper/",
        image: "/packages/web2mobile-wrapper.svg",
        href: "/docs/packages/web2mobile-wrapper",
      },
    ],
  },
  {
    name: "Starter Templates",
    iconKey: "template",
    description: "Production-ready templates to jumpstart your projects",
    color: "teal",
    packages: [
      {
        name: "SvelteKit + Better Auth + Drizzle",
        icon: "Layers",
        description: "Full-stack SvelteKit app with Better Auth, Drizzle ORM on Cloudflare D1, Stripe payments, and shadcn-svelte components.",
        longDescription: "A full-stack SvelteKit starter that deploys to Cloudflare. Better Auth handles sign-in, Drizzle ORM talks to a D1 database, Stripe takes payments, and shadcn-svelte supplies the UI — wired together so you start on product features instead of plumbing.",
        commands: ["bun create starter-app", "npx create-starter-app"],
        path: "starter-templates/template-svelte-betterauth-shadcn-drizzle/",
        image: "/packages/template-svelte-betterauth-shadcn-drizzle.svg",
        href: github("starter-templates/template-svelte-betterauth-shadcn-drizzle/"),
      },
      {
        name: "Next.js + Better Auth + Drizzle",
        icon: "Layers",
        description: "Next.js SaaS boilerplate with PostgreSQL, Better Auth, Stripe subscriptions, and shadcn/ui components.",
        longDescription: "A Next.js SaaS boilerplate with the boring parts done: Better Auth with pre-built auth UI, PostgreSQL through Drizzle ORM, Stripe subscriptions, UploadThing file uploads and shadcn/ui, organised as a Turborepo and linted with Biome.",
        commands: ["bun create starter-app", "npx create-starter-app"],
        path: "starter-templates/template-nextjs-betterauth-shadcn-drizzle/",
        image: "/packages/template-nextjs-betterauth-shadcn-drizzle.svg",
        href: github("starter-templates/template-nextjs-betterauth-shadcn-drizzle/"),
      },
      {
        name: "Next.js SaaS on Cloudflare",
        icon: "Layers",
        description: "Next.js SaaS template with Better Auth, Stripe billing, teams, a dashboard and 50 colour themes, deployed to Cloudflare.",
        longDescription: "A feature-rich Next.js SaaS starter for Cloudflare: Better Auth with social and Sign-In-With-Ethereum login, Stripe subscriptions, teams, an interactive charts dashboard, a docs section, and 50 light and dark colour themes built on Tailwind and shadcn/ui.",
        commands: ["bun create starter-app", "npx create-starter-app"],
        path: "starter-templates/template-nextjs-harness-cloudflare/",
        image: "/packages/template-nextjs-harness-cloudflare.svg",
        href: github("starter-templates/template-nextjs-harness-cloudflare/"),
      },
      {
        name: "Fumadocs Documentation",
        icon: "BookOpen",
        description: "Documentation site with Fumadocs, Orama search, OpenAPI/Swagger docs, MDX support, and collapsible sidebar.",
        longDescription: "The template this site grew from. Fumadocs on Next.js 16 with Orama full-text search, OpenAPI reference pages, interactive dependency graphs and file trees, AI integrations and MDX — all configured from one site config file.",
        commands: ["bun create starter-app", "npx create-starter-app"],
        path: "starter-templates/template-fumadocs/",
        image: "/packages/template-fumadocs.svg",
        href: github("starter-templates/template-fumadocs/"),
      },
      {
        name: "Docusaurus Documentation",
        icon: "BookOpen",
        description: "Docusaurus 3 docs template with offline Lunr search, OpenAPI plugin, and classic theme optimized for technical docs.",
        longDescription: "A Docusaurus 3 documentation template tuned for technical docs: the classic theme, offline Lunr search that needs no hosted index, and an OpenAPI plugin that renders API reference pages from your spec.",
        commands: ["bun create starter-app", "npx create-starter-app"],
        path: "starter-templates/template-docusaurus/",
        image: "/packages/template-docusaurus.svg",
        href: github("starter-templates/template-docusaurus/"),
      },
    ],
  },
]
